type TypeName =
  | 'TimelineTweet'
  | 'TimelineTimelineItem'
  | 'TimelineUser'
  | 'TimelineTimelineCursor'
  | 'TweetWithVisibilityResults'
  | 'ContextualTweetInterstitial'
  | 'TimelineTimelineModule'
  | 'TweetTombstone'
  | 'TimelinePrompt'
  | 'TimelineMessagePrompt'
  | 'TimelineCommunity'
  | 'TimelineTombstone'
  | 'TimelineTrend'
  | 'TimelineNotification'
  | 'TimelineNotificationAggregateUserActions'
  | 'TweetUnavailable'
  | 'TweetPreviewDisplay'
  | 'Tweet'
  | 'User'
  | 'UserUnavailable'
  | 'Community'
  | 'CommunityDeleteActionUnavailable'
  | 'CommunityJoinAction'
  | 'CommunityJoinActionUnavailable'
  | 'CommunityLeaveActionUnavailable'
  | 'CommunityTweetPinActionUnavailable'
  | 'CommunityTweetUnpinActionUnavailable'
  | 'CommunityInvitesUnavailable'
  | 'CommunityJoinRequestsUnavailable'
  | 'ApiImage';

export type { TypeName };
