name: CI

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            configs:
              - 'packages/configs/**'
            core:
              - 'packages/core/**'
            auth:
              - 'packages/auth/**'
            client:
              - 'packages/client/**'
            models:
              - 'packages/models/**'
            x:
              - 'packages/x/**'
            rednote:
              - 'packages/rednote/**'

  lint:
    runs-on: ubuntu-latest
    needs: filter
    strategy:
      matrix:
        package: ${{ fromJSON(needs.filter.outputs.changes) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint --filter @social-sdk/${{ matrix.package }}

  test:
    runs-on: ubuntu-latest
    needs: [filter]
    strategy:
      matrix:
        package: ${{ fromJSON(needs.filter.outputs.changes) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test:ci --filter @social-sdk/${{ matrix.package }}
