export const defaultConfig = {
  appId: 'xhs-pc-web',
  callFrom: 'web',
  carryDeviceInfo: false,
  includes: ['xiaohongshu.com'],
  process461Response: true,
  captchaInCurrent: false,
  isHidden: 'visible',
  platform: 'Mac OS',
  forceLoginHook: undefined,
  xsIgnore: [],
  configInit: false,
  autoReload: false,
  disableMns: false,
  spamCallback: undefined,
  onCaptchaClose: undefined,
  onReadyToLoadJS: undefined,
  loadTimeout: 4000,
};
